CoffeeShop/Models/ShoppingCart.cs
namespace CoffeeShop.Models
{
    public class ShoppingCart
    {
        public int Id { get; set; }
        public Product? Product { get; set; }
        public int Qty { get; set; }
        public string? ShoppingCartId { get; set; }
    }
}

CoffeeShop/Controllers/OrdersController.cs
using CoffeeShop.Models;
using CoffeeShop.Models.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace CoffeeShop.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IOrderRespository _orderRespository;
        private readonly IShoppingCartRepository _shoppingCartRepository;

        public OrdersController(IOrderRespository orderRespository, IShoppingCartRepository shoppingCartRepository)
        {
            _orderRespository = orderRespository ?? throw new ArgumentNullException(nameof(orderRespository));
            _shoppingCartRepository = shoppingCartRepository ?? throw new ArgumentNullException(nameof(shoppingCartRepository));
        }

        public IActionResult Checkout()
        {
            var shoppingCartItems = _shoppingCartRepository.GetShoppingCart();
            if (shoppingCartItems == null || shoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty. Please add some items before checking out.");
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Orders order)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(order);
                }

                var shoppingCartItems = _shoppingCartRepository.GetShoppingCart();
                if (shoppingCartItems == null || shoppingCartItems.Count == 0)
                {
                    ModelState.AddModelError("", "Your cart is empty. Please add some items before checking out.");
                    return View(order);
                }

                order.OrderTotal = _shoppingCartRepository.GetShoppingCartTotal();
                order.OrderPlaced = DateTime.Now;

                _orderRespository.PlaceOrder(order);
                _shoppingCartRepository.ClearCart();
                HttpContext.Session.SetInt32("CartCount", 0);

                return RedirectToAction("CheckoutComplete");
            }
            catch (Exception ex)
            {
                // Log the exception
                // logger.LogError(ex, "Error occurred while processing order");

                ModelState.AddModelError("", "An error occurred while processing your order. Please try again.");
                return View(order);
            }
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks for your order. You'll soon enjoy our delicious coffee!";
            return View();
        }
    }
}

CoffeeShop/Controllers/ProductsController.cs
using CoffeeShop.Models.Interfaces;
using CoffeeShop.Models.Services;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductRepository productRepository;

        public ProductsController(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        public IActionResult Shop()
        {
            return View(productRepository.GetAllProducts());
        }

        public IActionResult Detail(int id)
        {
            var product = productRepository.GetProductDetails(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }
    }
}

CoffeeShop/Controllers/ShoppingCartController.cs
using CoffeeShop.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShoppingCartRepository shoppingCartRepository;
        private readonly IProductRepository productRepository;

        public ShoppingCartController(IShoppingCartRepository shoppingCartRepository, IProductRepository productRepository)
        {
            this.shoppingCartRepository = shoppingCartRepository;
            this.productRepository = productRepository;
        }

        public IActionResult Index()
        {
            var items = shoppingCartRepository.GetShoppingCart();
            shoppingCartRepository.ShoppingCart = items;
            ViewBag.CartTotal = shoppingCartRepository.GetShoppingCartTotal();
            return View(items);
        }

        public RedirectToActionResult AddToShoppingCart(int pId)
        {
            var product = productRepository.GetAllProducts().FirstOrDefault(p => p.Id == pId);
            if (product != null)
            {
                shoppingCartRepository.AddToCart(product);
                int cartCount = shoppingCartRepository.GetShoppingCart().Count;
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int pId)
        {
            var product = productRepository.GetAllProducts().FirstOrDefault(p => p.Id == pId);
            if (product != null)
            {
                shoppingCartRepository.RemoveFromCart(product);
                int cartCount = shoppingCartRepository.GetShoppingCart().Count;
                HttpContext.Session.SetInt32("CartCount", cartCount);
            }
            return RedirectToAction("Index");
        }
    }
}

CoffeeShop/Views/ShoppingCart/Index.cshtml
@model IEnumerable<ShoppingCart>

@if (Model.Count() > 0)
{
    <section class="h-100 h-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12">
                    <div class="card card-registration card-registration-2" style="border-radius: 15px; background-color:#fafafa">
                        <div class="card-body p-0">
                            <div class="row g-0">
                                <div class="col-lg-7">
                                    <div class="p-5">
                                        <div class="d-flex justify-content-between align-items-center mb-5">
                                            <h2 class="fw-bold mb-0 text-black">Shopping Cart</h2>
                                            <h6 class="mb-0 text-muted">@Model.Count() items</h6>
                                        </div>
                                        <hr class="my-4">

                                        @foreach (var item in Model)
                                        {
                                            <div class="row mb-4 d-flex justify-content-between align-items-center">
                                                <div class="col-md-2 col-lg-2 col-xl-2">
                                                    <img src="@item.Product.ImageUrl"
                                                         class="img-fluid rounded-3">
                                                </div>
                                                <div class="col-md-3 col-lg-3 col-xl-3">
                                                    <h6 class="text-black mb-0">@item.Qty x @item.Product.Name</h6>
                                                </div>

                                                <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                                    <h6 class="mb-0">(@item.Qty * @item.Product.Price) $</h6>
                                                </div>

                                                <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                                    <a asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-pId="@item.Product.Id" class="text-decoration-none"><h3>&#128465;</h3></a>
                                                </div>

                                            </div>

                                            <hr class="my-4">
                                        }






                                        <div class="pt-5">
                                            <h6 class="mb-0">
                                                <a asp-controller="Products" asp-action="Shop" class="text-body">
                                                    <i class="fas fa-long-arrow-alt-left me-2"></i>Back to shop
                                                </a>
                                            </h6>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-5 bg-grey">
                                    <div class="p-5">
                                        <h4 class="fw-bold mb-5 mt-2 pt-1">Summary</h4>
                                        <hr class="my-4">
                                        <div class="d-flex justify-content-between mb-5">
                                            <h5 class="text-uppercase">Total price</h5>
                                            <h5>@ViewBag.CartTotal.ToString("c") </h5>
                                        </div>

                                        <a asp-controller="Orders" asp-action="Checkout">
                                            <button type="button"
                                                    class="btn btn-primary w-100 text-center"
                                                    data-mdb-ripple-color="dark">
                                                Proceed
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

else
{
    <div class="container">
        <br><br><br><br>
        <div class="text-center">
            <img src="https://www.svgrepo.com/show/17356/empty-cart.svg" class="img-fluid" style="width: 200px; height: 200px; margin-left: auto; margin-right: auto" alt="...">
            <br>
            <h1><strong>Your cart is empty</strong></h1>
            <br>
            <p>Before proceed to checkout you must add some products to your shopping cart. You will find a lot of interesting products on our "Shop" page.</p>
            <a asp-controller="Products" asp-action="Shop" class="btn btn-primary w-20">
                Start Shopping
            </a>
        </div>
    </div>
}


     